# Generated by Django 4.2.11 on 2025-03-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('per_hour', 'Per Hour'), ('negotiable', 'Negotiable'), ('free', 'Free')], default='fixed', max_length=10),
        ),
    ]
