# Generated by Django 4.2.11 on 2025-03-28 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0002_ad_price_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SPAM', 'Spamming'), ('SCAM', 'Scamming / Fraud'), ('HACK', 'Hacking / Malicious Activity'), ('OTHER', 'Other (See Details)')], help_text='The primary reason for flagging this user.', max_length=10)),
                ('details', models.TextField(blank=True, help_text="Provide specific details, especially if 'Other' reason is selected.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('RESOLVED', 'Resolved')], db_index=True, default='PENDING', max_length=10)),
                ('flagged_user', models.ForeignKey(help_text='The user being reported.', on_delete=django.db.models.deletion.CASCADE, related_name='flags_received', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(help_text='The moderator who submitted this flag.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Flag',
                'verbose_name_plural': 'User Flags',
                'ordering': ['-created_at'],
            },
        ),
    ]
